apiVersion: v1
kind: Service
metadata:
  name: nginx-gitops-svc
spec:
  type: ClusterIP
  selector:
    app: label4pod # Deployment가 생성하는 pod에 할당 및 관리 label과  동일해야 함(Spec Template 또는 Spec  Selector) 
  ports:
  - port: 80
    targetPort: 80
